version: '3'
services:
  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    container_name: nats-con
    environment:
      - STAN_CLUSTER_ID=alancid
    command: ["--cluster_id=alancid"]